CNPM/TH_CNPM/DoAnhDuy/BookStoreManager/Controllers/BillController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BookStoreManager.Models;

namespace BookStoreManager.Controllers
{
    public class BillController : Controller
    {
        private BookStoreEntities db = new BookStoreEntities();

        // GET: Bill
        public ActionResult Index()
        {
            var dATSACHes = db.DATSACHes.Include(d => d.KHACHHANG);
            return View(dATSACHes.ToList());
        }

        // GET: Bill/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DATSACH dATSACH = db.DATSACHes.Find(id);
            if (dATSACH == null)
            {
                return HttpNotFound();
            }
            return View(dATSACH);
        }

        // GET: Bill/Create
        public ActionResult Create()
        {
            ViewBag.MaKhachHang = new SelectList(db.KHACHHANGs, "MaKhachHang", "HoTen");
            return View();
        }

        // POST: Bill/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaDatSach,NgayDat,MaKhachHang,DiaChiGiaoHang")] DATSACH dATSACH)
        {
            if (ModelState.IsValid)
            {
                db.DATSACHes.Add(dATSACH);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaKhachHang = new SelectList(db.KHACHHANGs, "MaKhachHang", "HoTen", dATSACH.MaKhachHang);
            return View(dATSACH);
        }

        // GET: Bill/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DATSACH dATSACH = db.DATSACHes.Find(id);
            if (dATSACH == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaKhachHang = new SelectList(db.KHACHHANGs, "MaKhachHang", "HoTen", dATSACH.MaKhachHang);
            return View(dATSACH);
        }

        // POST: Bill/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaDatSach,NgayDat,MaKhachHang,DiaChiGiaoHang")] DATSACH dATSACH)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dATSACH).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaKhachHang = new SelectList(db.KHACHHANGs, "MaKhachHang", "HoTen", dATSACH.MaKhachHang);
            return View(dATSACH);
        }

        // GET: Bill/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DATSACH dATSACH = db.DATSACHes.Find(id);
            if (dATSACH == null)
            {
                return HttpNotFound();
            }
            return View(dATSACH);
        }

        // POST: Bill/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DATSACH dATSACH = db.DATSACHes.Find(id);
            db.DATSACHes.Remove(dATSACH);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CNPM/TH_CNPM/DoAnhDuy/BookStoreManager/Controllers/BillDetailController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BookStoreManager.Models;

namespace BookStoreManager.Controllers
{
    public class BillDetailController : Controller
    {
        private BookStoreEntities db = new BookStoreEntities();

        // GET: BillDetail
        public ActionResult Index()
        {
            var cHITTIETDATSACHes = db.CHITTIETDATSACHes.Include(c => c.SACH).Include(c => c.DATSACH);
            return View(cHITTIETDATSACHes.ToList());
        }

        // GET: BillDetail/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CHITTIETDATSACH cHITTIETDATSACH = db.CHITTIETDATSACHes.Find(id);
            if (cHITTIETDATSACH == null)
            {
                return HttpNotFound();
            }
            return View(cHITTIETDATSACH);
        }

        // GET: BillDetail/Create
        public ActionResult Create()
        {
            ViewBag.MaSach = new SelectList(db.SACHes, "MaSach", "TenSach");
            ViewBag.MADATSACH = new SelectList(db.DATSACHes, "MaDatSach", "MaDatSach");
            return View();
        }

        // POST: BillDetail/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaChiTietDatSach,MaSach,Soluong,UnitPrice,MADATSACH")] CHITTIETDATSACH cHITTIETDATSACH)
        {
            if (ModelState.IsValid)
            {
                db.CHITTIETDATSACHes.Add(cHITTIETDATSACH);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaSach = new SelectList(db.SACHes, "MaSach", "TenSach", cHITTIETDATSACH.MaSach);
            ViewBag.MADATSACH = new SelectList(db.DATSACHes, "MaDatSach", "MaDatSach", cHITTIETDATSACH.MADATSACH);
            return View(cHITTIETDATSACH);
        }

        // GET: BillDetail/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CHITTIETDATSACH cHITTIETDATSACH = db.CHITTIETDATSACHes.Find(id);
            if (cHITTIETDATSACH == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaSach = new SelectList(db.SACHes, "MaSach", "TenSach", cHITTIETDATSACH.MaSach);
            ViewBag.MADATSACH = new SelectList(db.DATSACHes, "MaDatSach", "DiaChiGiaoHang", cHITTIETDATSACH.MADATSACH);
            return View(cHITTIETDATSACH);
        }

        // POST: BillDetail/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaChiTietDatSach,MaSach,Soluong,UnitPrice,MADATSACH")] CHITTIETDATSACH cHITTIETDATSACH)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cHITTIETDATSACH).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaSach = new SelectList(db.SACHes, "MaSach", "TenSach", cHITTIETDATSACH.MaSach);
            ViewBag.MADATSACH = new SelectList(db.DATSACHes, "MaDatSach", "DiaChiGiaoHang", cHITTIETDATSACH.MADATSACH);
            return View(cHITTIETDATSACH);
        }

        // GET: BillDetail/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CHITTIETDATSACH cHITTIETDATSACH = db.CHITTIETDATSACHes.Find(id);
            if (cHITTIETDATSACH == null)
            {
                return HttpNotFound();
            }
            return View(cHITTIETDATSACH);
        }

        // POST: BillDetail/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CHITTIETDATSACH cHITTIETDATSACH = db.CHITTIETDATSACHes.Find(id);
            db.CHITTIETDATSACHes.Remove(cHITTIETDATSACH);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CNPM/TH_CNPM/DoAnhDuy/BookStoreManager/Views/BillDetail/Create.cshtml
@model BookStoreManager.Models.CHITTIETDATSACH

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h3 style="color:red; text-align:center;">Têm chi tiết hóa đơn</h3>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.MADATSACH, "Mã hóa đơn", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("MADATSACH", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.MADATSACH, "", new { @class = "text-danger" })
                </div>
            </div>
            <br />
            <div class="form-group">
                @Html.LabelFor(model => model.MaSach, "Tên sách", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("MaSach", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.MaSach, "", new { @class = "text-danger" })
                </div>
            </div>
            <br />
            <div class="form-group">
                @Html.LabelFor(model => model.Soluong, "Số lượng", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Soluong, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Soluong, "", new { @class = "text-danger" })
                </div>
            </div>
            <br />
            <div class="form-group">
                @Html.LabelFor(model => model.UnitPrice, "Tổng tiền", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.UnitPrice, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.UnitPrice, "", new { @class = "text-danger" })
                </div>
            </div>

            <br />

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </div>
        </div>
    }

    <div>
        <a style="margin-top:10px;" class="btn btn-danger" href="@Url.Action("Index","BillDetail")"><i class="fa-solid fa-arrow-left"></i> Bill detail</a>

    </div>
</div>

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

CNPM/TH_CNPM/DoAnhDuy/BookStoreManager/Views/BillDetail/Delete.cshtml
@model BookStoreManager.Models.CHITTIETDATSACH

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CHITTIETDATSACH</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Soluong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Soluong)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UnitPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UnitPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SACH.TenSach)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SACH.TenSach)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DATSACH.DiaChiGiaoHang)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DATSACH.DiaChiGiaoHang)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CNPM/TH_CNPM/DoAnhDuy/BookStoreManager/Views/BillDetail/Details.cshtml
@model BookStoreManager.Models.CHITTIETDATSACH

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>CHITTIETDATSACH</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Soluong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Soluong)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UnitPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UnitPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SACH.TenSach)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SACH.TenSach)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DATSACH.DiaChiGiaoHang)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DATSACH.DiaChiGiaoHang)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MaChiTietDatSach }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CNPM/TH_CNPM/DoAnhDuy/BookStoreManager/Views/BillDetail/Edit.cshtml
@model BookStoreManager.Models.CHITTIETDATSACH

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CHITTIETDATSACH</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaChiTietDatSach)

        <div class="form-group">
            @Html.LabelFor(model => model.MaSach, "MaSach", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaSach", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaSach, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Soluong, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Soluong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Soluong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UnitPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UnitPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UnitPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MADATSACH, "MADATSACH", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MADATSACH", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MADATSACH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

CNPM/TH_CNPM/DoAnhDuy/BookStoreManager/Views/BillDetail/Index.cshtml
@model IEnumerable<BookStoreManager.Models.CHITTIETDATSACH>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h2 style="text-align:center;color:aquamarine">Chi tiết hóa đơn</h2>

    <p>
        <a  class="btn btn-primary" href="@Url.Action("Create","BillDetail")"><i class="fa-solid fa-plus"></i> New Detail</a>
        <a class="btn btn-danger" href="@Url.Action("Index","Bill")"><i class="fa-solid fa-check"></i> Bill List</a>    </p>
    <table class="table">
        <tr>
            <th>
                Mã hóa đơn
            </th>
            <th>
                Tên sách
            </th>
            <th>
                Số lượng
            </th>
            <th>
                Tổng tiền
            </th>

        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.MADATSACH)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SACH.TenSach)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Soluong)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UnitPrice)
                </td>
            </tr>
        }

    </table>
</div>